global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hybrid-crawler-monitor'

rule_files:
  - "alerts.yml"

scrape_configs:
  # Hybrid Crawler Application
  - job_name: 'hybrid-crawler'
    static_configs:
      - targets: ['hybrid-crawler:8000']
        labels:
          service: 'hybrid-crawler'
          environment: 'production'
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL Exporter (optional)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'

  # Redis Exporter (optional)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  # Kafka Exporter (optional)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
        labels:
          service: 'kafka'

  # Node Exporter (System Metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []  # Add AlertManager URL if configured
