version: "3.9"

# Capstone local infrastructure stack (MSA-friendly)
# Services:
# - MongoDB (no auth, dev only)
# - Postgres with pgvector extension (vector DB)
# - Redpanda (Kafka API compatible) + Console
#
# After starting, set your microservices env to:
#   MONGO_URI=mongodb://localhost:27017
#   MONGO_DB=analysis
#   VECTOR_DB_URL=postgresql://postgres:postgres@localhost:5432/vectors
#   KAFKA_BROKERS=localhost:19092
#   MESSAGE_BUS=kafka
#
# Copy .env.example to .env to override Postgres credentials if desired.

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - capstone

  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-vectors}
    ports:
      - "5432:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data
      - ./pgvector/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
    networks:
      - capstone

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.6
    container_name: redpanda
    restart: unless-stopped
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "9092:9092"     # internal clients (containers) + host mapped
      - "19092:19092"   # host access with advertised listener
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    networks:
      - capstone

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.7.1
    container_name: redpanda-console
    restart: unless-stopped
    environment:
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - redpanda
    ports:
      - "8080:8080"
    networks:
      - capstone

networks:
  capstone:
    driver: bridge

volumes:
  mongo-data:
  pgvector-data:
  redpanda-data:
