version: '3.8'

services:
  # ===========================================
  # Infrastructure Services
  # ===========================================
  
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-spring-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-osint_db}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - postgres-spring-data:/var/lib/postgresql/data
      - ../db/postgres/init-osint.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - spring-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: redis-spring-dev
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-spring-data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  consul:
    image: consul:1.15
    container_name: consul-spring-dev
    restart: unless-stopped
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -bind=0.0.0.0
    environment:
      CONSUL_BIND_INTERFACE: eth0
    volumes:
      - consul-spring-data:/consul/data
      - consul-spring-config:/consul/config
    ports:
      - "${CONSUL_HTTP_PORT:-8500}:8500"
      - "${CONSUL_DNS_PORT:-8600}:8600/udp"
      - "${CONSUL_SERVER_PORT:-8300}:8300"
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # ===========================================
  # Spring Boot Microservices
  # ===========================================
  
  api-gateway:
    image: pension/api-gateway:local
    build:
      context: ../../services/java
      dockerfile: gateway/Dockerfile
    container_name: api-gateway-spring
    restart: unless-stopped
    environment:
      # Spring Configuration
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      PORT: ${GATEWAY_PORT:-8080}
      
      # Service URLs (using ENV format matching Spring Boot config)
      SERVICES_COLLECTOR_URL: http://collector-service:8002
      SERVICES_ANALYSIS_URL: http://analysis-service:8001
      SERVICES_ABSA_URL: http://absa-service:8003
      SERVICES_ALERT_URL: http://alert-service:8004
      SERVICES_OSINT_ORCHESTRATOR_URL: http://osint-orchestrator:8005
      SERVICES_OSINT_PLANNING_URL: http://osint-planning:8006
      SERVICES_OSINT_SOURCE_URL: http://osint-source:8007
      
      # Consul Configuration (disabled for now due to Spring Cloud compatibility)
      SPRING_CLOUD_CONSUL_ENABLED: ${CONSUL_ENABLED:-false}
      SPRING_CLOUD_CONSUL_HOST: ${CONSUL_HOST:-consul}
      SPRING_CLOUD_CONSUL_PORT: ${CONSUL_PORT:-8500}
      SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED: ${CONSUL_DISCOVERY_ENABLED:-false}
      SPRING_CLOUD_CONSUL_CONFIG_ENABLED: ${CONSUL_CONFIG_ENABLED:-false}
      SPRING_CLOUD_COMPATIBILITY_VERIFIER_ENABLED: false
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    ports:
      - "${GATEWAY_PORT:-8080}:${GATEWAY_PORT:-8080}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      analysis-service:
        condition: service_started
      collector-service:
        condition: service_started
      absa-service:
        condition: service_started
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${GATEWAY_PORT:-8080}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  collector-service:
    image: pension/collector-service:local
    build:
      context: ../../services/java
      dockerfile: collector/Dockerfile
    container_name: collector-service-spring
    restart: unless-stopped
    environment:
      # Spring Configuration
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      PORT: 8002
      
      # Database Configuration
      DB_URL: jdbc:postgresql://postgres:5432/${DB_NAME:-osint_db}
      DB_USERNAME: ${DB_USER:-osint_user}
      DB_PASSWORD: ${DB_PASSWORD:-osint_password}
      
      # Consul Configuration (disabled for now)
      SPRING_CLOUD_CONSUL_ENABLED: ${CONSUL_ENABLED:-false}
      SPRING_CLOUD_CONSUL_HOST: ${CONSUL_HOST:-consul}
      SPRING_CLOUD_CONSUL_PORT: ${CONSUL_PORT:-8500}
      SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED: ${CONSUL_DISCOVERY_ENABLED:-false}
      SPRING_CLOUD_COMPATIBILITY_VERIFIER_ENABLED: false
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    ports:
      - "8002:8002"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  analysis-service:
    image: pension/analysis-service:local
    build:
      context: ../../services/java
      dockerfile: analysis/Dockerfile
    container_name: analysis-service-spring
    restart: unless-stopped
    environment:
      # Spring Configuration
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      PORT: 8001
      
      # Database Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-osint_db}
      DB_USER: ${DB_USER:-osint_user}
      DB_PASSWORD: ${DB_PASSWORD:-osint_password}
      HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO:-update}
      
      # Consul Configuration (disabled for now)
      SPRING_CLOUD_CONSUL_ENABLED: ${CONSUL_ENABLED:-false}
      SPRING_CLOUD_CONSUL_HOST: ${CONSUL_HOST:-consul}
      SPRING_CLOUD_CONSUL_PORT: ${CONSUL_PORT:-8500}
      SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED: ${CONSUL_DISCOVERY_ENABLED:-false}
      SPRING_CLOUD_COMPATIBILITY_VERIFIER_ENABLED: false
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      HIBERNATE_LOG_LEVEL: ${HIBERNATE_LOG_LEVEL:-INFO}
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  absa-service:
    image: pension/absa-service:local
    build:
      context: ../../services/java
      dockerfile: absa/Dockerfile
    container_name: absa-service-spring
    restart: unless-stopped
    environment:
      # Spring Configuration
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      PORT: 8003
      
      # Database Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-osint_db}
      DB_USER: ${DB_USER:-osint_user}
      DB_PASSWORD: ${DB_PASSWORD:-osint_password}
      HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO:-update}
      
      # Consul Configuration (disabled for now)
      SPRING_CLOUD_CONSUL_ENABLED: ${CONSUL_ENABLED:-false}
      SPRING_CLOUD_CONSUL_HOST: ${CONSUL_HOST:-consul}
      SPRING_CLOUD_CONSUL_PORT: ${CONSUL_PORT:-8500}
      SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED: ${CONSUL_DISCOVERY_ENABLED:-false}
      SPRING_CLOUD_COMPATIBILITY_VERIFIER_ENABLED: false
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      HIBERNATE_LOG_LEVEL: ${HIBERNATE_LOG_LEVEL:-INFO}
    ports:
      - "8003:8003"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  spring-network:
    driver: bridge
    name: spring-dev-network

volumes:
  postgres-spring-data:
  redis-spring-data:
  consul-spring-data:
  consul-spring-config:
